### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by Sleepydesu** [EnderdracheLP/BeatSaberServerBrowserQuest#1]
There is a glitch where after joining a lobby, all of the audio from the quest (even outside of beat saber) can be cut and to fix it you would need to restart the headset. I'm not sure how it is caused or a way to fix it properly without a headset reset.

**Comment by michael-r-elp** [comment]
If it requires a headset restart it's more than likely an issue on the headset end, as no mod can affect anything outside the game

**Comment by Sleepydesu** [comment]
Do you know a fix for it other than a restart?

**Comment by michael-r-elp** [comment]
Not at the moment, but I guess you could try looking up the issue with all the audio dissappearing, the last time I had that issue is a long time ago though and it only ever happened 2 times to me
