### ISSUE TITLE
Cannot display third-party BeatTogether servers

### ISSUE THREAD

**Issue by WGzeyu** [EnderdracheLP/BeatSaberServerBrowserQuest#2]
These servers can be displayed normally in the ServerBrowser of the PC, but they do not appear in the ServerBrowser of Quest.
In theory, these servers also support cross play.

![](https://wgzeyu.gtxcn.com/img/bs/QQ%E6%88%AA%E5%9B%BE20211118210437.png)

**Comment by michael-r-elp** [comment]
Thanks, this might be an issue on the server end filtering specific servers out for the quest version of the mod, I'll get in contact with the owner of the API and I'll let you know once we have that sorted out

**Comment by michael-r-elp** [comment]
Just got informed by the site owner, that it should now be fixed and returning other servers, let me know if it works now or not

**Comment by WGzeyu** [comment]
Now it works, thanks!

![](https://wgzeyu.gtxcn.com/img/bs/QQ%E6%88%AA%E5%9B%BE20211119023609.png)
